/*
 * @(#)Props.java	1.12 02/12/17
 *
 * Copyright (c) 1996-2002 Sun Microsystems, Inc.  All rights reserved.
 */

package com.sun.media.customizer;


public class Props extends java.util.ListResourceBundle  {

 	public Object[][] getContents(){
		return contents;
	}

	static final Object[][] contents = {

	    // Customizer
	{"customizer.Customize" , "Customize"},
	{"customizer.Quit" , "Quit"},
	{"customizer.Next" , "Next>>"},
	{"customizer.Back" , "<<Back"},
	{"customizer.Help" , "Help"},
	{"customizer.DlgQuestion" , "Target file already exists, overwrite?"},
	{"customizer.DlgTitle" , "Confirm"},
	{"JMFCustomizer.Title" , "JMF Customizer"},

	// GeneralPane
	{"GeneralPane.Browse", "Browse..."},
	{"GeneralPane.SrcJar", "Source JAR:"},
	{"GeneralPane.DstJar", "Target JAR:"},
	{"GeneralPane.MFILES", "Media Files"},
	{"GeneralPane.CAPTURE", "Capture"},
	{"GeneralPane.RTPRECV", "RTP Receive"},
	{"GeneralPane.PLAY", "Play"},
	{"GeneralPane.RTPTRANS", "RTP Transmit"},
	{"GeneralPane.TRANSCODE", "Transcode"},
	{"GeneralPane.GUI", "GUI"},
	{"GeneralPane.DEMO", "Demo & Tool"},
	{"GeneralPane.BEAN", "Player bean"},
	{"GeneralPane.MSOURCE", "Media Source"},
	{"GeneralPane.MSINK", "Media Sink"},
	{"GeneralPane.OPTCOMP", "Optional Component"},
	{"GeneralPane.s1s1", "At least need one source and one sink"},
	{"GeneralPane.WRONGSEL", "Wrong Selection"},
	{"GeneralPane.BADTARJAR","Bad Target JAR" },
	{"GeneralPane.BADSRCJAR","Bad Source JAR" },
	{"GeneralPane.SRCJARNOTEXIST","Source JAR file doesn't exist or is empty" },
	{"GeneralPane.INPUTSRCJAR","Please input source JAR file" },
	{"GeneralPane.INPUTDSTJAR","Please input target JAR file" },
	{"GeneralPane.SRCDSTJAR","Source and target jar files are the same" },
	{"GeneralPane.twoJar","Generate two target jar files." },
	// ProtocolPane
	{"ProtocolPane.FILE", "file"},
	{"ProtocolPane.HTTP", "http"},
	{"ProtocolPane.HTTPS", "https"},
	{"ProtocolPane.FTP", "ftp"},
	{"ProtocolPane.RTP", "rtp"},
	{"ProtocolPane.RTSP", "rtsp"},
	{"ProtocolPane.JAVASOUND", "javasound"},
	{"ProtocolPane.PROTOCOL", "Protocol"},
	{"ProtocolPane.VFW", "VFW"},
	{"ProtocolPane.SVDO", "SunVideo"},
	{"ProtocolPane.SVDOPLS", "SunVideo+"},
	{"ProtocolPane.CLNMGDS", "Cloneable/Merging DataSource"},
	{"ProtocolPane.DSOUND", "Direct Sound"},
	// MFormatPane
	{"MFormatPane.TITLE", "Source Media Formats"},
	{"MFormatPane.AU", "Au"},
	{"MFormatPane.AIFF", "Aiff"},
	{"MFormatPane.GSM", "Gsm"},
	{"MFormatPane.MP2", "Mp2"},
	{"MFormatPane.MP3", "Mp3"},
	{"MFormatPane.WAV", "Wav"},
	{"MFormatPane.MOV", "Quicktime (.mov)"},
	{"MFormatPane.AVI", "Avi"},
	{"MFormatPane.MPEG", "Mpeg"},
	{"MFormatPane.MVR", "Hotmedia (.mvr)"},
	{"MFormatPane.MIDI", "MIDI"},
	{"MFormatPane.RMF", "RMF"},
	{"MFormatPane.CDAUDIO", "CDAudio"},
	// MuxPane
	{"MuxPane.GSM", "Gsm"},
	{"MuxPane.MP2", "MP2"},
	{"MuxPane.MP3", "MP3"},
	{"MuxPane.WAV", "Wav"},
	{"MuxPane.AIFF", "Aiff"},
	{"MuxPane.AU", "Au"},
	{"MuxPane.MOV", "Quicktime (.mov)"},
	{"MuxPane.AVI", "Avi"},
	{"MuxPane.ATITLE", "Audio Multiplexer"},
	{"MuxPane.VTITLE", "Video Multiplexer"},
	// CodecPane
	/*
	{"CodecPane.MPA", "MP3/2"},
	{"CodecPane.MSADPCM", "MSADPCM"},
	{"CodecPane.ULAW", "U-law"},
	{"CodecPane.ALAW", "A-law"},
	{"CodecPane.GSM", "Gsm"},
	{"CodecPane.DVI", "Dvi"},
	{"CodecPane.IMA4", "IMA4"},
	{"CodecPane.IMA4_MS", "IMA4_MS"},
	{"CodecPane.GSM_MS", "Gsm_MS"},
	{"CodecPane.MPARTP", "MP3/2_RTP"},
	{"CodecPane.ULAWRTP", "Ulaw_RTP"},
	{"CodecPane.GSMRTP", "Gsm_RTP"},
	{"CodecPane.DVIRTP", "Dvi_RTP"},
	{"CodecPane.G723RTP", "G723_RTP"},
	{"CodecPane.CINEPAK", "Cinepak"},
	{"CodecPane.H263", "H263"},
	{"CodecPane.JPEGRTP", "Jpeg_RTP"},
	{"CodecPane.MPEGRTP", "Mpeg_RTP"},
	{"CodecPane.ACODEC", "Audio Codecs"},
	{"CodecPane.VCODEC", "Video Codecs"},
	{"CodecPane.JPEG", "JPEG"},
	*/
	{"CodecPane.MPAJD", "JD_MP2"},
	{"CodecPane.ULAWJD", "JD_U-law"},
	{"CodecPane.MSGSMJD", "JD_Gsm-MS"},
	{"CodecPane.GSMJD", "JD_Gsm"},
	{"CodecPane.ALAWJD", "JD_A-law"},
	{"CodecPane.MSIMA4JD", "JD_IMA4-MS"},
	{"CodecPane.IMA4JD", "JD_IMA4"},
	{"CodecPane.DVIJD", "JD_Dvi"},
	{"CodecPane.G723JD", "JD_G723"},
	{"CodecPane.MSADPCMJD", "JD_MSADPCM"},
	{"CodecPane.MPAND", "ND_MP2"},
	{"CodecPane.MSGSMND", "ND_Gsm-MS"},
	{"CodecPane.GSMND", "ND_Gsm"},
	{"CodecPane.G723ND", "ND_G723"},
	{"CodecPane.ACMND", "ND_ACM"},
	{"CodecPane.CINEPAKJD", "JD_Cinepak"},
	{"CodecPane.H263JD", "JD_H263"},
	{"CodecPane.CINEPAKND", "ND_Cinepak"},
	{"CodecPane.H263ND", "ND_H263"},
	{"CodecPane.H261ND", "ND_H261"},
	{"CodecPane.JPEGND", "ND_Jpeg"},
	{"CodecPane.MPEGND", "ND_Mpeg"},
	{"CodecPane.IV32ND", "ND_IV32"},
	{"CodecPane.VCMND", "ND_VCM"},
	{"CodecPane.MPEGPLY", "MPEG Player"},
	{"CodecPane.ULAWJE", "JE_U-law"},
	{"CodecPane.MSGSMJE", "JE_Gsm-MS"},
	{"CodecPane.GSMJE", "JE_Gsm"},
	{"CodecPane.MSIMA4JE", "JE_IMA4-MS"},
	{"CodecPane.IMA4JE", "JE_IMA4"},
	{"CodecPane.DVIJE", "JE_Dvi"},
	{"CodecPane.MPANE", "NE_MP2"},
	{"CodecPane.MSGSMNE", "NE_Gsm-MS"},
	{"CodecPane.GSMNE", "NE_Gsm"},
	{"CodecPane.G723NE", "NE_G723"},
	{"CodecPane.ACMNE", "NE_ACM"},
	{"CodecPane.CINEPAKPRONE", "NE_CinepakPro"},
	{"CodecPane.H263NE", "NE_H263"},
	{"CodecPane.JPEGNE", "NE_Jpeg"},
	{"CodecPane.VCMNE", "NE_VCM"},
	{"CodecPane.MPADRTP", "DRTP_MP3/2"},
	{"CodecPane.ULAWDRTP", "DRTP_U-law"},
	{"CodecPane.GSMDRTP", "DRTP_Gsm"},
	{"CodecPane.DVIDRTP", "DRTP_Dvi"},
	{"CodecPane.G723DRTP", "DRTP_G723"},
	{"CodecPane.H263DRTP", "DRTP_H263"},
	{"CodecPane.H261DRTP", "DRTP_H261"},
	{"CodecPane.JPEGDRTP", "DRTP_Jpeg"},
	{"CodecPane.MPEGDRTP", "DRTP_Mpeg"},
	{"CodecPane.MPAPRTP", "PRTP_MP3/2"},
	{"CodecPane.ULAWPRTP", "PRTP_U-law"},
	{"CodecPane.GSMPRTP", "PRTP_Gsm"},
	{"CodecPane.DVIPRTP", "PRTP_Dvi"},
	{"CodecPane.G723PRTP", "PRTP_G723"},
	{"CodecPane.H263PRTP", "PRTP_H263"},
	{"CodecPane.JPEGPRTP", "PRTP_Jpeg"},
	{"CodecPane.MPEGPRTP", "PRTP_Mpeg"},
	{"CodecPane.ADECODER", "Audio Decoders"},
	{"CodecPane.VDECODER", "Video Decoders"},
	{"CodecPane.AENCODER", "Audio Encoders"},
	{"CodecPane.VENCODER", "Video Encoders"},
	{"CodecPane.ADEPAC", "Audio Depacketizers"},
	{"CodecPane.VDEPAC", "Video Depacketizers"},
	{"CodecPane.APAC", "Audio Packetizers"},
	{"CodecPane.VPAC", "Video Packetizers"},
	// RendererPane
	{"RendererPane.SUNAUDIO", "SunAudio"},
	{"RendererPane.JAVASOUND", "JavaSound"},
	{"RendererPane.DAUDIO", "DirectAudio"},
	{"RendererPane.AWT", "AWT"},
	{"RendererPane.JPEG", "JPEG"},
	{"RendererPane.XLIB", "XLib"},
	{"RendererPane.XIL", "XIL"},
	{"RendererPane.SUNRAY", "SunRay"},
	{"RendererPane.DDRAW", "DirectDraw"},
	{"RendererPane.GDI", "GDI"},
	{"RendererPane.ARNDR", "Audio Renderer"},
	{"RendererPane.VRNDR", "Video Renderer"},
	// ProcessJAR
	{"ProcessJAR.WRT", "Writing Target JAR File ..."},
	{"ProcessJAR.REGISTRY", "Updating JMF Registry ..."},
	// ProgressDiag
	{"ProgressDiag.DTITLE", "Customizing..."},
	{"ProgressDiag.ERR", "Error"},
	{"ProgressDiag.SRCJAR", "Source JAR"},
	{"ProgressDiag.TJAR", "Target JAR"},
	{"ProgressDiag.FN", "File Name :  "},
	{"ProgressDiag.FS", "File Size :  "},
	{"ProgressDiag.NOC", "Number of Classes : "},
	{"ProgressDiag.LOAD", "Loading Source JAR File ..."},
	{"ProgressDiag.DONE", "Done"},
	// HelperDiag
	{"HelperDiag.TITLE", "JMFCustomizer Help"},
	{"HelperDiag.ERROR", "Can't find the CustomizerHelp.html"},
	/** Don't translate the following strings **/
	{"jmf.properties", "jmf.properties"},
	{"jmf.default.font", "Helvetica"}

	};
}


