/*
 * @(#)JmpxEvent.java	1.2 02/08/21
 *
 * Copyright (c) 1996-2002 Sun Microsystems, Inc.  All rights reserved.
 */

package com.sun.media.codec.video.jmpx;

/**
 * A base class for the events generated by mpx.
 */
public class JmpxEvent {
}
