/*
 * @(#)JmpxStatsUpdateEvent.java	1.2 02/08/21
 *
 * Copyright (c) 1996-2002 Sun Microsystems, Inc.  All rights reserved.
 */

package com.sun.media.codec.video.jmpx;


/**
 * An event generated by mpx.
 */
public class JmpxStatsUpdateEvent extends JmpxEvent {
    double fps, kbps, loc;
    long time, size;

    public double getFPS() {
	return fps;
    }

    public double getKBPS() {
	return kbps;
    }

    public double getLoc() {
	return loc;
    }

    public long getTime() {
	return time;
    }

    public long getSize() {
	return size;
    }
}

