/*
 * @(#)JmpxFileDoneEvent.java	1.2 02/08/21
 *
 * Copyright (c) 1996-2002 Sun Microsystems, Inc.  All rights reserved.
 */

package com.sun.media.codec.video.jmpx;

/**
 * An event generated by mpx.
 */
public class JmpxFileDoneEvent extends JmpxEvent {
    double fps, kbps;
    long time, frames;
    long size;

    public double getFPS() {
	return fps;
    }

    public double getKBPS() {
	return kbps;
    }

    public long getTime() {
	return time;
    }

    public long getFrames() {
	return frames;
    }

    public long getSize() {
	return size;
    }
}

