/*
 * @(#)helptxt.h	1.2 02/08/21
 *
 * Copyright (c) 1996-2002 Sun Microsystems, Inc.  All rights reserved.
 */

"\n"
"   M p e g E x p e r t\n"
"\n"
"Copyright (C) 1994,1995 Sun Microsystems, All Rights Reserved\n"
"MpegExpert and Sun Microsystems are Trademarks of Sun Microsystems. \n"
"\n"
"\n"
"   Q U I C K   H E L P   F O R    M p e g E x p e r t:\n"
"   \n"
"   Also refer to MpegExpert User's Manual, the full documentation for this\n"
"   software. Reading the manual once, will always save you time.\n"
"\n"
"__ Having problems with the CD_TOOL or the CAPTURE_TOOL ?\n"
"   Read the User's manual and any relevant release notes, if you are still\n"
"   having problems, read them again more carefully.\n"
"     \n"
"__ To randomly jump anywhere in the data source, press on the left mouse\n"
"   button (once !) while pointing with the position cursor to the corresponding\n"
"   location on the position bar. Position bar is the thin bar in the display\n"
"   window, which is below the control buttons. When you move the cursor into\n"
"   the display window, it becomes an up-down arrow cursor.\n"
"   \n"
"__ Playback control buttons from left to right are for: pause/step_fwd,\n"
"   slow_fwd, normal_play, fast_fwd, jump_bwd, jump_fwd, begin_location_marker,\n"
"   and end_location_marker (markers are used with the Capture_Tool).  \n"
"\n"
"__ Video and Audio pulldown menus enable you to dynamically switch between\n"
"   different video_display and audio_playback modes. Higher quality and stereo\n"
"   audio modes require more processing power. Likewise, Zoomed display modes\n"
"   require more processing power. Find the combination which is best suited\n"
"   to your needs.  \n"
"   \n"
"__ Use the Data pulldown menu at the top menu bar to set the data type of the\n"
"   Mpeg source, BEFORE opening it. \n"
"\n"
"__ Tracks pulldown menu options only apply if the current data source type is\n"
"   ISO11172 ( Systems level Mpeg Data with multiplexed audio-video streams).\n"
"   Use these options to selectively play audio and video streams.\n"
"\n"
"__ PROBLEM in playing an Mpeg sequence which even the freebee players seem to\n"
"   play? Well, MpegExpert by default expects real, systems level, multiplexed\n"
"   audio+video Mpeg streams. Almost all Mpeg sequences you will find at public\n"
"   ftp sites are video only sequences. To be able to play such sequences, you\n"
"   have to change the default data type to 'VideoSeq', from the Data pulldown\n"
"   menu at the top menu bar. Do this before opening the file.\n"
"\n"
"\n"
"THIS SOFTWARE IS OWNED BY Sun Microsystems. ALL THE CONCEPTS, ALGORITHMS,\n"
"APPLICATION AND USER INTERFACE FEATURES USED IN IT ARE COPYRIGHTED, PROTECTED,\n"
"INTELLECTUAL PROPERTY OF Sun Microsystems.  YOU HAVE A RIGHT TO USE LICENCE FOR\n"
"THIS SOFTWARE IN AGREEMENT WITH THE SOFTWARE LICENCE AGREEMENT APV_0.51. YOU\n"
"HAVE AGREED NOT TO REVERSE ENGINEER, DECOMPILE, DISASSEMBLE OR MODIFY THIS\n"
"SOFTWARE OR INSPECT ITS OBJECT CODE UNDER ANY CONDITIONS OR FOR ANY PURPOSE\n"
"WHATSOEVER.\n"
